### ISSUE TITLE
ch_19 UnicodeDecodeError when reading when reading movies.dat

### ISSUE THREAD

**Issue by sixo** [lmassaron/ml4dummies_2ed#2]
The following code (assumes utf-8) fails when reading the movie.dat database at themoment
```
movies = pd.read_table('ml-1m/movies.dat', sep='::', 
         header=None, names=['movie_id', 'title', 
         'genres'], engine='python')
```

I need to specify `'iso-8859-1'` encoding for panda to parse the data correctly
```
movies = pd.read_table('ml-1m/movies.dat', sep='::', 
         header=None, names=['movie_id', 'title', 
         'genres'], engine='python', encoding='iso-8859-1')
```

**Comment by lmassaron** [comment]
movie.dat has been updated the last time on 2019-12-03 and it seems that at that time some latin-1 encoded character has been inserted into this specific file (but not in the other ones). This problem seems not to be present on the ml-10m version and probably it is won't be found even in other larger available files. 

It is clearly specific of that file and probably not amendable. In fact, as stated by the readme disclaimer: "Neither the University of Minnesota nor any of the researchers involved can guarantee the correctness of the data, its suitability for any particular purpose, or the validity of results based on the use of the data set".

Thank you @sixo for having us notice this problem. At the moment, our stance on this problem is to monitor the situation and decide on the next edition of the book what to do based on the pandas package version we will be using. In fact, a more reasonable fix, without adhering to a specific encoding that may change undocumented along the time, would be to use the `encoding_errors` parameter, as of pandas version 1.3.0:

`movies = pd.read_table('ml-1m/movies.dat', sep='::', header=None, 
                                       names=['movie_id', 'title', 'genres'], engine='python', 
                                       encoding_errors='replace')`
